name: bmad-react-native
version: "1.0.0"
description: "React Native Cross-Platform Mobile Development Expansion Pack"
author: "BMad-Method Community"
category: "mobile-development"

agents:
  - mobile-architect
  - mobile-dev
  - mobile-ux
  - mobile-sm
  - mobile-qa

dependencies:
  react-native: ">=0.70.0"
  node: ">=20.0.0"
  ios: ">=13.0"
  android: ">=21"

features:
  - react-native-development
  - ios-app-development
  - android-app-development
  - cross-platform-mobile
  - mobile-architecture
  - mobile-ux-design
  - mobile-sprint-management

installation:
  type: "copy"
  source: "."
  destination: "bmad-core/expansion-packs/bmad-react-native"

compatibility:
  bmad-method: ">=4.0.0"